In [1]:
import pandas as pd

In [2]:
boosting_df = pd.DataFrame({'model': ['Ada Boost',
  'Gradient Boosting',
  'Hist Gradient Boosting',
  'Random Forest'],
 'explained variance score': ['0.664320011',
  '0.744387315',
  '0.714108384',
  '0.725741767'],
 'mae score': ['0.509707', '0.322739', '0.346004', '0.320631'],
 'mse score': ['0.447138', '0.299437', '0.333122', '0.319691'],
 'r2 score': ['0.615889', '0.742771', '0.713833', '0.725371'],
 'mean fit time': [0.06111502647399902,
  0.09474420547485352,
  0.20879764556884767,
  0.22972640991210938]}
)

In [3]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree Best Params',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.519170173', '0.582505685', '0.604044373'],
 'mae score': ['0.453352', '0.412381', '0.403526'],
 'mse score': ['0.561051', '0.486007', '0.461048'],
 'r2 score': ['0.518032', '0.582499', '0.603940'],
 'mean fit time': [0.0038480281829833983, 0.002916717529296875, 0.0]})

In [4]:
knn_df = pd.DataFrame({'model': ['Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.296105449', '0.458032567'],
 'mae score': ['0.534009', '0.459355'],
 'mse score': ['0.819923', '0.631994'],
 'r2 score': ['0.295650', '0.457089'],
 'mean fit time': [0.002267265319824219, 0.00196380615234375]})

In [5]:
lasso_df = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.323697558',
  '0.000000000',
  '0.000000000',
  '0.000000000'],
 'mae score': ['0.598191', '0.754756', '0.754756', '0.754756'],
 'mse score': ['0.794388', '1.165777', '1.165777', '1.165777'],
 'r2 score': ['0.317586', '-0.001454', '-0.001454', '-0.001454'],
 'mean fit time': [0.0019822120666503906,
  0.001965951919555664,
  0.0,
  0.001387166976928711]})

In [6]:
linear_df_county = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination',
  'PolynomialFeatures'],
 'explained variance score': ['0.516160331',
  '0.154246870',
  '0.515382968',
  '0.577558754',
  '0.516160331'],
 'mae score': ['0.561105', '0.687690', '0.562143', '0.508230', '0.561105'],
 'mse score': ['0.582223', '1.004720', '0.582986', '0.521283', '0.582223'],
 'r2 score': ['0.504008', '0.144085', '0.503357', '0.555922', '0.504008'],
 'mean fit time': [0.002126932144165039,
  0.002436113357543945,
  0.0009799480438232421,
  0.003066873550415039,
  0.0032428741455078126]})

In [7]:
linear_df_major = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination',
  'PolynomialFeatures'],
 'explained variance score': ['0.323697558',
  '0.346584400',
  '0.317366860',
  '0.366576019',
  '0.323697558'],
 'mae score': ['0.598191', '0.573226', '0.589659', '0.578973', '0.598191'],
 'mse score': ['0.794388', '0.764308', '0.803951', '0.742302', '0.794388'],
 'r2 score': ['0.317586', '0.343426', '0.309371', '0.362330', '0.317586'],
 'mean fit time': [0.00394906997680664,
  0.001230907440185547,
  0.003142642974853516,
  0.0032642364501953127,
  0.004418134689331055]})

In [8]:
linear_df_minor = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination',
  'PolynomialFeatures'],
 'explained variance score': ['0.009793441',
  '0.000000000',
  '-0.014661771',
  '-0.014661771',
  '0.009793441'],
 'mae score': ['1.090351', '1.125011', '1.093935', '1.093935', '1.090351'],
 'mse score': ['1.436593', '2.589643', '1.508375', '1.508375', '1.436593'],
 'r2 score': ['-0.071071', '-0.930742', '-0.124589', '-0.124589', '-0.071071'],
 'mean fit time': [0.0013183116912841796,
  0.0026300430297851564,
  0.0010371685028076171,
  0.0023096084594726564,
  0.0031280040740966795]})

In [9]:
ridge_df = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.323697558',
  '0.346193254',
  '0.317646904',
  '0.365849865'],
 'mae score': ['0.598191', '0.573166', '0.588934', '0.579849'],
 'mse score': ['0.794388', '0.764735', '0.803411', '0.742962'],
 'r2 score': ['0.317586', '0.343059', '0.309834', '0.361762'],
 'mean fit time': [0.0020092487335205077,
  0.00023837089538574218,
  0.0009173870086669922,
  0.0]})

In [10]:
boosting_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Ada Boost,0.664320011,0.509707,0.447138,0.615889,0.061115
1,Gradient Boosting,0.744387315,0.322739,0.299437,0.742771,0.094744
2,Hist Gradient Boosting,0.714108384,0.346004,0.333122,0.713833,0.208798
3,Random Forest,0.725741767,0.320631,0.319691,0.725371,0.229726

In [11]:
decision_tree_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Decision Tree Best Params,0.519170173,0.453352,0.561051,0.518032,0.003848
1,Recursive Feature Elimination,0.582505685,0.412381,0.486007,0.582499,0.002917
2,Sequential Feature Selector,0.604044373,0.403526,0.461048,0.603940,0.000000

In [12]:
knn_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.296105449,0.534009,0.819923,0.295650,0.002267
1,Sequential Feature Selector,0.458032567,0.459355,0.631994,0.457089,0.001964

In [13]:
lasso_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.323697558,0.598191,0.794388,0.317586,0.001982
1,Select From Model,0.000000000,0.754756,1.165777,-0.001454,0.001966
2,Sequential Feature Selector,0.000000000,0.754756,1.165777,-0.001454,0.000000
3,Recursive Feature Elimination,0.000000000,0.754756,1.165777,-0.001454,0.001387

In [14]:
linear_df_county

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.516160331,0.561105,0.582223,0.504008,0.002127
1,Select From Model,0.154246870,0.687690,1.004720,0.144085,0.002436
2,Sequential Feature Selector,0.515382968,0.562143,0.582986,0.503357,0.000980
3,Recursive Feature Elimination,0.577558754,0.508230,0.521283,0.555922,0.003067
4,PolynomialFeatures,0.516160331,0.561105,0.582223,0.504008,0.003243

In [15]:
linear_df_major

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.323697558,0.598191,0.794388,0.317586,0.003949
1,Select From Model,0.346584400,0.573226,0.764308,0.343426,0.001231
2,Sequential Feature Selector,0.317366860,0.589659,0.803951,0.309371,0.003143
3,Recursive Feature Elimination,0.366576019,0.578973,0.742302,0.362330,0.003264
4,PolynomialFeatures,0.323697558,0.598191,0.794388,0.317586,0.004418

In [16]:
linear_df_minor

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.009793441,1.090351,1.436593,-0.071071,0.001318
1,Select From Model,0.000000000,1.125011,2.589643,-0.930742,0.002630
2,Sequential Feature Selector,-0.014661771,1.093935,1.508375,-0.124589,0.001037
3,Recursive Feature Elimination,-0.014661771,1.093935,1.508375,-0.124589,0.002310
4,PolynomialFeatures,0.009793441,1.090351,1.436593,-0.071071,0.003128

In [17]:
ridge_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.323697558,0.598191,0.794388,0.317586,0.002009
1,Select From Model,0.346193254,0.573166,0.764735,0.343059,0.000238
2,Sequential Feature Selector,0.317646904,0.588934,0.803411,0.309834,0.000917
3,Recursive Feature Elimination,0.365849865,0.579849,0.742962,0.361762,0.000000