In [1]:
import pandas as pd

In [2]:
boosting_df = pd.DataFrame({'model': ['Ada Boost',
  'Gradient Boosting',
  'Hist Gradient Boosting',
  'Random Forest'],
 'explained variance score': ['0.664320011',
  '0.744387315',
  '0.714108384',
  '0.725741767'],
 'mae score': ['0.509707', '0.322739', '0.346004', '0.320631'],
 'mse score': ['0.447138', '0.299437', '0.333122', '0.319691'],
 'r2 score': ['0.615889', '0.742771', '0.713833', '0.725371'],
 'mean fit time': [0.06111502647399902,
  0.09474420547485352,
  0.20879764556884767,
  0.22972640991210938]}
)

In [3]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree Best Params',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.519170173', '0.582505685', '0.604044373'],
 'mae score': ['0.453352', '0.412381', '0.403526'],
 'mse score': ['0.561051', '0.486007', '0.461048'],
 'r2 score': ['0.518032', '0.582499', '0.603940'],
 'mean fit time': [0.0038480281829833983, 0.002916717529296875, 0.0]})

In [4]:
knn_df = pd.DataFrame({'model': ['Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.296105449', '0.458032567'],
 'mae score': ['0.534009', '0.459355'],
 'mse score': ['0.819923', '0.631994'],
 'r2 score': ['0.295650', '0.457089'],
 'mean fit time': [0.002267265319824219, 0.00196380615234375]})

In [5]:
lasso_df = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.323697558',
  '0.323697807',
  '0.317366500',
  '0.303484118'],
 'mae score': ['356,689.532731',
  '356,689.556870',
  '351,601.668755',
  '365,600.244645'],
 'mse score': ['282,444,458,713.029724',
  '282,444,213,590.306152',
  '285,844,478,716.262329',
  '289,689,244,582.361755'],
 'r2 score': ['0.317586', '0.317586', '0.309371', '0.300082'],
 'mean fit time': [0.0031407833099365234,
  0.0,
  0.0016278743743896485,
  0.0004551410675048828]})

In [6]:
linear_df_county = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination',
  'PolynomialFeatures'],
 'explained variance score': ['0.516160331',
  '0.154246870',
  '0.515382968',
  '0.560936336',
  '0.516160331'],
 'mae score': ['409,105.844545',
  '501,399.901283',
  '409,862.904440',
  '390,273.000058',
  '409,105.844545'],
 'mse score': ['309,508,371,378.781067',
  '534,106,879,331.563354',
  '309,914,161,659.730347',
  '282,560,370,658.778381',
  '309,508,371,378.822815'],
 'r2 score': ['0.504008', '0.144085', '0.503357', '0.547192', '0.504008'],
 'mean fit time': [0.0009873867034912109,
  0.0008823871612548828,
  0.0,
  0.0014740943908691407,
  0.003798770904541016]})

In [7]:
linear_df_major = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination',
  'PolynomialFeatures'],
 'explained variance score': ['0.323697558',
  '0.346584400',
  '0.317366860',
  '0.366576019',
  '0.323697558'],
 'mae score': ['0.598191', '0.573226', '0.589659', '0.578973', '0.598191'],
 'mse score': ['0.794388', '0.764308', '0.803951', '0.742302', '0.794388'],
 'r2 score': ['0.317586', '0.343426', '0.309371', '0.362330', '0.317586'],
 'mean fit time': [0.00394906997680664,
  0.001230907440185547,
  0.003142642974853516,
  0.0032642364501953127,
  0.004418134689331055]})

In [8]:
linear_df_minor = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination',
  'PolynomialFeatures'],
 'explained variance score': ['0.009793441',
  '-0.000000000',
  '-0.014661771',
  '-0.020393418',
  '0.009793441'],
 'mae score': ['315,352.476958',
  '325,376.923077',
  '316,388.888889',
  '317,928.144519',
  '315,352.476958'],
 'mse score': ['120,169,307,096.928299',
  '216,620,566,134.122284',
  '126,173,792,962.963013',
  '124,112,070,932.307205',
  '120,169,307,096.928345'],
 'r2 score': ['-0.071071', '-0.930742', '-0.124589', '-0.106213', '-0.071071'],
 'mean fit time': [0.001712799072265625,
  0.0011720657348632812,
  0.0,
  0.0006044864654541016,
  0.002858734130859375]})

In [9]:
ridge_df = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.323697558',
  '0.346193254',
  '0.317646904',
  '0.365849865'],
 'mae score': ['0.598191', '0.573166', '0.588934', '0.579849'],
 'mse score': ['0.794388', '0.764735', '0.803411', '0.742962'],
 'r2 score': ['0.317586', '0.343059', '0.309834', '0.361762'],
 'mean fit time': [0.0020092487335205077,
  0.00023837089538574218,
  0.0009173870086669922,
  0.0]})

In [10]:
boosting_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Ada Boost,0.664320011,0.509707,0.447138,0.615889,0.061115
1,Gradient Boosting,0.744387315,0.322739,0.299437,0.742771,0.094744
2,Hist Gradient Boosting,0.714108384,0.346004,0.333122,0.713833,0.208798
3,Random Forest,0.725741767,0.320631,0.319691,0.725371,0.229726

In [11]:
decision_tree_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Decision Tree Best Params,0.519170173,0.453352,0.561051,0.518032,0.003848
1,Recursive Feature Elimination,0.582505685,0.412381,0.486007,0.582499,0.002917
2,Sequential Feature Selector,0.604044373,0.403526,0.461048,0.603940,0.000000

In [12]:
knn_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.296105449,0.534009,0.819923,0.295650,0.002267
1,Sequential Feature Selector,0.458032567,0.459355,0.631994,0.457089,0.001964

In [13]:
lasso_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.323697558,"356,689.532731","282,444,458,713.029724",0.317586,0.003141
1,Select From Model,0.323697807,"356,689.556870","282,444,213,590.306152",0.317586,0.000000
2,Sequential Feature Selector,0.317366500,"351,601.668755","285,844,478,716.262329",0.309371,0.001628
3,Recursive Feature Elimination,0.303484118,"365,600.244645","289,689,244,582.361755",0.300082,0.000455

In [14]:
linear_df_county

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.516160331,"409,105.844545","309,508,371,378.781067",0.504008,0.000987
1,Select From Model,0.154246870,"501,399.901283","534,106,879,331.563354",0.144085,0.000882
2,Sequential Feature Selector,0.515382968,"409,862.904440","309,914,161,659.730347",0.503357,0.000000
3,Recursive Feature Elimination,0.560936336,"390,273.000058","282,560,370,658.778381",0.547192,0.001474
4,PolynomialFeatures,0.516160331,"409,105.844545","309,508,371,378.822815",0.504008,0.003799

In [15]:
linear_df_major

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.323697558,0.598191,0.794388,0.317586,0.003949
1,Select From Model,0.346584400,0.573226,0.764308,0.343426,0.001231
2,Sequential Feature Selector,0.317366860,0.589659,0.803951,0.309371,0.003143
3,Recursive Feature Elimination,0.366576019,0.578973,0.742302,0.362330,0.003264
4,PolynomialFeatures,0.323697558,0.598191,0.794388,0.317586,0.004418

In [16]:
linear_df_minor

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.009793441,"315,352.476958","120,169,307,096.928299",-0.071071,0.001713
1,Select From Model,-0.000000000,"325,376.923077","216,620,566,134.122284",-0.930742,0.001172
2,Sequential Feature Selector,-0.014661771,"316,388.888889","126,173,792,962.963013",-0.124589,0.000000
3,Recursive Feature Elimination,-0.020393418,"317,928.144519","124,112,070,932.307205",-0.106213,0.000604
4,PolynomialFeatures,0.009793441,"315,352.476958","120,169,307,096.928345",-0.071071,0.002859

In [17]:
ridge_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.323697558,0.598191,0.794388,0.317586,0.002009
1,Select From Model,0.346193254,0.573166,0.764735,0.343059,0.000238
2,Sequential Feature Selector,0.317646904,0.588934,0.803411,0.309834,0.000917
3,Recursive Feature Elimination,0.365849865,0.579849,0.742962,0.361762,0.000000