In [1]:
import pandas as pd

In [2]:
boosting_df = pd.DataFrame({'model': ['Ada Boost',
  'Gradient Boosting',
  'Hist Gradient Boosting',
  'Random Forest'],
 'explained variance score': ['0.309311667',
  '0.699047770',
  '0.637113535',
  '0.631574270'],
 'mae score': ['0.647211', '0.354180', '0.377455', '0.376502'],
 'mse score': ['0.851915', '0.320033', '0.385532', '0.391075'],
 'r2 score': ['0.197421', '0.698500', '0.636794', '0.631573'],
 'mean fit time': [0.06627044677734376,
  0.1663498878479004,
  0.5150489330291748,
  1.018368673324585]})

In [3]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree Best Params',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.607022934', '0.402868694', '0.521889680'],
 'mae score': ['0.406570', '0.490007', '0.433889'],
 'mse score': ['0.418572', '0.634940', '0.507817'],
 'r2 score': ['0.605668', '0.401830', '0.521591'],
 'mean fit time': [0.007033395767211914,
  0.008786249160766601,
  0.0033133506774902345]})

In [4]:
knn_df = pd.DataFrame({'model': ['Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.490679694', '0.403786924'],
 'mae score': ['0.452091', '0.501350'],
 'mse score': ['0.540687', '0.632917'],
 'r2 score': ['0.490625', '0.403736'],
 'mean fit time': [0.003085613250732422, 0.003519439697265625]})

In [5]:
lasso_df = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.443753983',
  '0.000000000',
  '0.000000000',
  '0.000000000'],
 'mae score': ['0.489823', '0.690619', '0.690619', '0.690619'],
 'mse score': ['0.591349', '1.065395', '1.065395', '1.065395'],
 'r2 score': ['0.442896', '-0.003697', '-0.003697', '-0.003697'],
 'mean fit time': [0.0012514591217041016,
  0.001845073699951172,
  0.0031268119812011717,
  0.0018747806549072265]})

In [6]:
linear_df = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination',
  'PolynomialFeatures'],
 'explained variance score': ['0.443753983',
  '0.384521827',
  '0.442032250',
  '0.442032250',
  '0.443753983'],
 'mae score': ['0.489823', '0.513834', '0.488051', '0.488051', '0.489823'],
 'mse score': ['0.591349', '0.654516', '0.593202', '0.593202', '0.591349'],
 'r2 score': ['0.442896', '0.383388', '0.441151', '0.441151', '0.442896'],
 'mean fit time': [0.0030014514923095703,
  0.0,
  0.0,
  0.0,
  0.0009646892547607421]})

In [7]:
ridge_df = pd.DataFrame({'model': ['Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.443753983',
  '0.384490444',
  '0.442001297',
  '0.442001297'],
 'mae score': ['0.489823', '0.513759', '0.488021', '0.488021'],
 'mse score': ['0.591349', '0.654552', '0.593236', '0.593236'],
 'r2 score': ['0.442896', '0.383354', '0.441119', '0.441119'],
 'mean fit time': [0.0007420063018798828,
  0.003318023681640625,
  0.0031248092651367187,
  0.0]})

In [8]:
boosting_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Ada Boost,0.309311667,0.647211,0.851915,0.197421,0.066270
1,Gradient Boosting,0.699047770,0.354180,0.320033,0.698500,0.166350
2,Hist Gradient Boosting,0.637113535,0.377455,0.385532,0.636794,0.515049
3,Random Forest,0.631574270,0.376502,0.391075,0.631573,1.018369

In [9]:
decision_tree_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Decision Tree Best Params,0.607022934,0.406570,0.418572,0.605668,0.007033
1,Recursive Feature Elimination,0.402868694,0.490007,0.634940,0.401830,0.008786
2,Sequential Feature Selector,0.521889680,0.433889,0.507817,0.521591,0.003313

In [10]:
knn_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.490679694,0.452091,0.540687,0.490625,0.003086
1,Sequential Feature Selector,0.403786924,0.501350,0.632917,0.403736,0.003519

In [11]:
lasso_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.443753983,0.489823,0.591349,0.442896,0.001251
1,Select From Model,0.000000000,0.690619,1.065395,-0.003697,0.001845
2,Sequential Feature Selector,0.000000000,0.690619,1.065395,-0.003697,0.003127
3,Recursive Feature Elimination,0.000000000,0.690619,1.065395,-0.003697,0.001875

In [12]:
linear_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.443753983,0.489823,0.591349,0.442896,0.003001
1,Select From Model,0.384521827,0.513834,0.654516,0.383388,0.000000
2,Sequential Feature Selector,0.442032250,0.488051,0.593202,0.441151,0.000000
3,Recursive Feature Elimination,0.442032250,0.488051,0.593202,0.441151,0.000000
4,PolynomialFeatures,0.443753983,0.489823,0.591349,0.442896,0.000965

In [13]:
ridge_df

,model,explained variance score,mae score,mse score,r2 score,mean fit time
0,Best Params,0.443753983,0.489823,0.591349,0.442896,0.000742
1,Select From Model,0.384490444,0.513759,0.654552,0.383354,0.003318
2,Sequential Feature Selector,0.442001297,0.488021,0.593236,0.441119,0.003125
3,Recursive Feature Elimination,0.442001297,0.488021,0.593236,0.441119,0.000000